-- hits
select 'Inserting hits';
INSERT INTO hits (
        hit_id,
        target_id,
        bean_id,
        contract_id,
        hit_start_date,
        hit_due_date,
        status,
        payment_id,
        location_id,
        weapon_purchase_id
    )
VALUES (
        1,
        1,
        3,
        13,
        '2025-01-04',
        '2025-02-17',
        'Failed',
        1,
        5,
        3
    );
INSERT INTO hits (
        hit_id,
        target_id,
        bean_id,
        contract_id,
        hit_start_date,
        hit_due_date,
        status,
        payment_id,
        location_id,
        weapon_purchase_id
    )
VALUES (
        2,
        2,
        2,
        1,
        '2025-02-01',
        '2025-03-08',
        'Scheduled',
        2,
        10,
        12
    );
INSERT INTO hits (
        hit_id,
        target_id,
        bean_id,
        contract_id,
        hit_start_date,
        hit_due_date,
        status,
        payment_id,
        location_id,
        weapon_purchase_id
    )
VALUES (
        3,
        3,
        7,
        10,
        '2025-01-06',
        '2025-02-23',
        'Completed',
        3,
        3,
        10
    );
INSERT INTO hits (
        hit_id,
        target_id,
        bean_id,
        contract_id,
        hit_start_date,
        hit_due_date,
        status,
        payment_id,
        location_id,
        weapon_purchase_id
    )
VALUES (
        4,
        12,
        8,
        13,
        '2025-01-07',
        '2025-03-09',
        'Active',
        4,
        6,
        14
    );
INSERT INTO hits (
        hit_id,
        target_id,
        bean_id,
        contract_id,
        hit_start_date,
        hit_due_date,
        status,
        payment_id,
        location_id,
        weapon_purchase_id
    )
VALUES (
        5,
        4,
        2,
        14,
        '2025-01-21',
        '2025-03-08',
        'Completed',
        5,
        2,
        6
    );
INSERT INTO hits (
        hit_id,
        target_id,
        bean_id,
        contract_id,
        hit_start_date,
        hit_due_date,
        status,
        payment_id,
        location_id,
        weapon_purchase_id
    )
VALUES (
        6,
        19,
        7,
        8,
        '2025-01-13',
        '2025-02-23',
        'Active',
        6,
        1,
        15
    );
INSERT INTO hits (
        hit_id,
        target_id,
        bean_id,
        contract_id,
        hit_start_date,
        hit_due_date,
        status,
        payment_id,
        location_id,
        weapon_purchase_id
    )
VALUES (
        8,
        9,
        20,
        7,
        '2025-02-11',
        '2025-02-28',
        'Failed',
        8,
        7,
        17
    );
INSERT INTO hits (
        hit_id,
        target_id,
        bean_id,
        contract_id,
        hit_start_date,
        hit_due_date,
        status,
        payment_id,
        location_id,
        weapon_purchase_id
    )
VALUES (
        11,
        14,
        7,
        6,
        '2025-02-04',
        '2025-02-19',
        'Failed',
        11,
        4,
        7
    );
INSERT INTO hits (
        hit_id,
        target_id,
        bean_id,
        contract_id,
        hit_start_date,
        hit_due_date,
        status,
        payment_id,
        location_id,
        weapon_purchase_id
    )
VALUES (
        12,
        7,
        4,
        20,
        '2025-01-30',
        '2025-03-08',
        'Completed',
        12,
        7,
        8
    );
INSERT INTO hits (
        hit_id,
        target_id,
        bean_id,
        contract_id,
        hit_start_date,
        hit_due_date,
        status,
        payment_id,
        location_id,
        weapon_purchase_id
    )
VALUES (
        13,
        13,
        9,
        12,
        '2025-02-13',
        '2025-02-28',
        'Failed',
        13,
        8,
        18
    );
INSERT INTO hits (
        hit_id,
        target_id,
        bean_id,
        contract_id,
        hit_start_date,
        hit_due_date,
        status,
        payment_id,
        location_id,
        weapon_purchase_id
    )
VALUES (
        15,
        14,
        12,
        16,
        '2025-01-30',
        '2025-03-02',
        'Completed',
        15,
        9,
        5
    );
INSERT INTO hits (
        hit_id,
        target_id,
        bean_id,
        contract_id,
        hit_start_date,
        hit_due_date,
        status,
        payment_id,
        location_id,
        weapon_purchase_id
    )
VALUES (
        16,
        2,
        13,
        8,
        '2025-01-25',
        '2025-03-11',
        'Completed',
        16,
        7,
        13
    );
INSERT INTO hits (
        hit_id,
        target_id,
        bean_id,
        contract_id,
        hit_start_date,
        hit_due_date,
        status,
        payment_id,
        location_id,
        weapon_purchase_id
    )
VALUES (
        20,
        9,
        10,
        8,
        '2025-01-02',
        '2025-03-02',
        'Completed',
        20,
        6,
        1
    );