SOURCE ../migrations/sql/V1__Database_Creation_Query.sql;
SOURCE ../migrations/sql/V2__Data_Insert_Query.sql;
SOURCE ./Run_All_Triggers_Query.sql;
SOURCE ./Database_Procs_Query.sql;
SOURCE ./Database_Events_Query.sql;
SOURCE ../migrations/sql/Views/R__Hit_Details.view.sql;
SOURCE ../migrations/sql/Views/R__Contract_Details.view.sql;
SOURCE ../migrations/sql/Views/R__Bean_Details.view.sql;
SOURCE ../migrations/sql/Functions/R__CalculatePaymentValue.sql;