on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{secrets.AWS_REGION}}
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Flyway Migrate
        uses: red-gate/FlywayGithubAction@v0.1.5
        with:
          url: ${{ secrets.DB_URL }}?sslMode=require
          user: ${{ secrets.DB_USER }}
          password: ${{ secrets.DB_PASSWORD }}
          locations: filesystem:./flyway/migrations/sql
          extraArgs: -outOfOrder=true

      