on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{secrets.AWS_REGION}}
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Setup Docker build
        uses: docker/setup-buildx-action@v3

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get short commit hash
        id: get-commit-sha
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build, tag and push to ECR
        id: build-ecr-image
        uses: docker/build-push-action@v5
        with:
          context: ./flyway
          file: ./flyway/Dockerfile
          push: true
          tags: |
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beans-flyway-migration:${{ steps.get-commit-sha.outputs.sha_short}}
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/beans-flyway-migration:latest
          cache-from: type:gha,scope=${{ github.workflow }}
          cache-to: type:gha,scope=${{ github.workflow }}, mode=max

      